# Generated by Django 5.2.6 on 2026-05-07 08:54

import django.db.models.deletion
import django.utils.timezone
import lote_registry.trustlists.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('display_name', models.CharField(max_length=100)),
                ('territory', models.CharField(help_text="ISO 3166-1 alpha-2 of the operator's MS, or 'EU' for cross-border", max_length=3)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('publisher', 'Publisher')], default='editor', max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', lote_registry.trustlists.models.OperatorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('pid', 'EU PID Providers'), ('wallet', 'EU Wallet Providers'), ('pubeaa', 'EU PubEAA Providers'), ('wrpac', 'EU WRPAC Providers'), ('wrprc', 'EU WRPRC Providers'), ('registrar', 'EU Registrars and Registers'), ('lotl', 'EU List of Trusted Lists')], max_length=16)),
                ('operator_names', models.JSONField(default=list, help_text='Array of {"language": "en", "value": "..."}')),
                ('scheme_name', models.JSONField(blank=True, default=list, help_text='Array of {"language": "en", "value": "..."}')),
                ('scheme_type', models.URLField(max_length=300)),
                ('territory', models.CharField(max_length=3)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['list_type', 'territory'],
            },
        ),
        migrations.CreateModel(
            name='PublishRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publish_runs', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publish_runs', to='trustlists.scheme')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotlPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.URLField(max_length=300)),
                ('scheme_territory', models.CharField(max_length=3)),
                ('scheme_type', models.URLField(max_length=300)),
                ('scheme_operator_names', models.JSONField(blank=True, default=list)),
                ('mime_type', models.CharField(choices=[('application/json', 'application/json'), ('application/xml', 'application/xml')], default='application/json', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(limit_choices_to={'list_type': 'lotl'}, on_delete=django.db.models.deletion.CASCADE, related_name='lotl_pointers', to='trustlists.scheme')),
            ],
            options={
                'ordering': ['scheme_territory', 'scheme_type'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.JSONField(default=list, help_text='Array of {"language", "value"}')),
                ('entity_id', models.URLField(max_length=300)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, help_text='PubEAA only — used as ServiceStatus on output.', max_length=128)),
                ('address', models.JSONField(blank=True, default=dict, help_text='{"postal": {...}, "electronic": [...]}')),
                ('information_uri', models.JSONField(blank=True, default=list)),
                ('services', models.JSONField(default=list, help_text='Array of service objects with serviceNames, serviceType, status')),
                ('cert_pem', models.TextField(blank=True, help_text='PEM-encoded X.509 (chain allowed)')),
                ('jwk', models.JSONField(blank=True, default=dict, help_text='JOSE JWK object')),
                ('did_uri', models.URLField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='trustlists.scheme')),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['scheme', 'entity_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scheme',
            constraint=models.UniqueConstraint(fields=('list_type', 'territory'), name='unique_list_type_territory'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('scheme', 'entity_id'), name='unique_scheme_entity_id'),
        ),
    ]
